<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\ChatSession;
use App\Models\Message; // Ensure you import your Message model
use Illuminate\Support\Facades\Http; 
use Illuminate\Support\Facades\Log;

class MessageController extends Controller
{
    // 1. INITIATE CHAT (Frontend calls this)
    public function sendMessage(Request $request, ChatSession $chatSession)
    {   
        if ($chatSession->user_id !== $request->user()->id) {
            abort(403, "You do not have permission to message in this chat.");
        }

        $validated = $request->validate([
            'message' => 'required|string',
        ]);

        // A. Save User Message
        $chatSession->messages()->create([
            'sender' => 'human',     
            'text' => $validated['message'], 
            'status' => 'completed' // Human messages are always done
        ]);

        // B. Create Placeholder Bot Message (The "Ticket")
        $botMessage = $chatSession->messages()->create([
            'sender' => 'LLM',        
            'text' => '', // Empty for now
            'status' => 'processing' // Mark as processing
        ]);

        // C. Call n8n (Fire and Forget)
        // We set a short timeout (5s). We just want to hand off the data.
        try {
            Http::timeout(5)->withHeaders([
                'X-API-KEY' => env('N8N_SECRET_KEY'),
                'Content-Type' => 'application/json',
            ])->post(env('N8N_WEBHOOK_URL'), [
                'message' => $validated['message'],
                'sessionId' => $chatSession->id,
                'bot_message_id' => $botMessage->id, // IMPORTANT: Pass the ID to n8n
                'callback_url' => route('api.n8n.callback') // Tell n8n where to reply
            ]);
        } catch (\Exception $e) {
            // Note: If n8n is set to "Wait for last node", this might timeout. 
            // That is expected and fine, as long as n8n received the data.
            Log::info("Hand-off to n8n complete (or timed out, which is fine).");
        }

        // D. Return the Ticket ID to Frontend immediately
        return response()->json([
            'user_message' => $validated['message'],
            'bot_message_id' => $botMessage->id,
            'status' => 'processing'
        ], 202); // 202 Accepted
    }

    // 2. CHECK STATUS (Frontend polls this)
    public function checkStatus($messageId)
    {
        $message = Message::findOrFail($messageId);

        return response()->json([
            'id' => $message->id,
            'status' => $message->status, // 'processing' or 'completed'
            'text' => $message->text
        ]);
    }

    // 3. RECEIVE CALLBACK (n8n calls this when done)
    public function handleCallback(Request $request)
    {
        // Validate incoming data from n8n
        $validated = $request->validate([
            'bot_message_id' => 'required|integer',
            'output' => 'required|string' // The text generated by AI
        ]);

        $message = Message::find($validated['bot_message_id']);

        if ($message) {
            $message->update([
                'text' => $validated['output'],
                'status' => 'completed'
            ]);
            return response()->json(['message' => 'Updated successfully'], 200);
        }

        return response()->json(['error' => 'Message not found'], 404);
    }
}